### ISSUE TITLE
NPM start - error  // throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#31]
``` c++
DEVELOPMENT mode
 70% 1/1 build modulesevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
npm ERR! webgui@0.0.1 start: `webpack-dev-server --hot --inline --progress --colors --devtool inline-source-map --content-base assets/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webgui@0.0.1 start script 'webpack-dev-server --hot --inline --progress --colors --devtool inline-source-map --content-base assets/'.
npm ERR! This is most likely a problem with the webgui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --progress --colors --devtool inline-source-map --content-base assets/
npm ERR! You can get their info via:
npm ERR!     npm owner ls webgui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xx/Git/graphene-ui/web/npm-debug.log

```

**Comment by c055** [comment]
caused to a additonal opened web ui CLI window
