### ISSUE TITLE
Promise not defined in bitshares-2-ui 2.0.151111

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#488]
When building the webpack:

```
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Blockchain/operations.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Icon/icon.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Blockchain/json-inspector.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Explorer/witnesses.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Exchange/exchange.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Utility/Box.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/components/Wallet/ImportKeys.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=expanded!./app/assets/stylesheets/app.scss
    Module build failed: ReferenceError: Promise is not defined
      at LazyResult.async (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
      at LazyResult.then (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
      at processCss (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/processCss.js:181:5)
      at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/css-loader/lib/loader.js:24:2)
```

**Comment by svk31** [comment]
I think that's one related to either using a too recent nodejs version or babel version.

**Comment by maqifrnswa** [comment]
Thanks - any tips on debugging? This didn't happen in 2.0.151105. I just did npm install in each of the directories then built the web pack

additional info:
Babel version  "version": "5.8.29" (which is what the web package.json asks for)
node version v0.10.25

**Comment by svk31** [comment]
Try updating node to v0.12.7, yours is quite old (even 0.12.7 is old)

**Comment by jcalfee** [comment]
The nvm makes thid  easy... Node version manager

**Comment by maqifrnswa** [comment]
~~It seems to be related to:
https://bitsharestalk.org/index.php?topic=19927.0~~
above is a different bug

you're right, you need a new version of node:
http://stackoverflow.com/questions/21564993/native-support-for-promises-in-node-js
Node.js added native promise support since version 0.11.13.

so we should depend on node > 0.11.13 (which is already recommended here:
https://github.com/cryptonomex/graphene-ui/blob/master/web/package.json#L9)

I can build it fine with node 5.0.0/ npm 3.3.6 if I use this patch:

```
diff --git a/web/app/assets/stylesheets/app.scss b/web/app/assets/stylesheets/app.scss
index 26f77e9..b976e10 100644
--- a/web/app/assets/stylesheets/app.scss
+++ b/web/app/assets/stylesheets/app.scss
@@ -1,5 +1,5 @@
 @import "./foundation_settings";
-@import "~react-foundation-apps/node_modules/foundation-apps/scss/foundation.scss";
+@import "~foundation-apps/scss/foundation.scss";
 @import "./foundation_overrides";
 @import "~react-tooltip/dist/react-tooltip.scss";
 @import "./forms";
```

**Comment by jonathanbahai** [comment]
Upgrade to latest iojs-v3.3.1 using nvm

Following this there are css-loader errors when you try to compile that have to do with newer version not including the es6-promise module.. so I went to:

conf/webpack.config.js

Added the following line to the top:

require('es6-promise').polyfill();

Then installed es6-promise:

npm install es6-promise

Then npm build run and npm build start all without any errors running the latest version.

Hope this helps you guys get started.. package maintainers please adjust to include these elements I mentioned for new builds from now on.

**Comment by wmbutler** [comment]
@valzav @svk31 some clarity here? Is it fixed, closed?

**Comment by svk31** [comment]
Yes you can close it, it's the same issue as Byron P had with the node version basically.
