### ISSUE TITLE
Duplicate () constructor in AccountOverview.jsx

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#554]
Error below when building 2.0.15.1125

```
ERROR in ./app/components/Account/AccountOverview.jsx
Module build failed: SyntaxError: /home/showard/sources/ui/bitshares-2-ui/web/app/components/Account/AccountOverview.jsx: Duplicate constructor in the same class (38:4)
  36 |     }
  37 | 
> 38 |     constructor() {
     |     ^
  39 |         super();
  40 |         this.state = {
  41 |             limit: 1000
    at Parser.pp.raise (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.parseClass (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/parser/statement.js:585:34)
    at Parser.pp.parseStatement (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/parser/statement.js:84:19)
    at Parser.parseStatement (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/plugins/flow.js:621:22)
    at Parser.pp.parseTopLevel (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at transpile (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/showard/sources/ui/bitshares-2-ui/web/node_modules/babel-loader/index.js:71:12)
 @ ./app/App.jsx 71:40-87
Child worker:
                             Asset    Size  Chunks             Chunk Names
    34e680c3bff4176537aa.worker.js  596 kB       0  [emitted]  main
        + 278 hidden modules
```

**Comment by svk31** [comment]
I think this is probably related to your version of babel-core or babel. Try reinstalling all your node modules and verifying your version of node.

**Comment by maqifrnswa** [comment]
thanks - fixed by deleting node_modules and reinstalling. My build scripts now always delete node_modules just to be safe
