### ISSUE TITLE
Notification systems should be unified

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#72]

**Comment by jcalfee** [comment]
This may be related... It appears on every page load:

```
Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at Notifier.componentWillReceiveProps (http://localhost:8080/app.js:147658:29)
    at Notifier.<anonymous> (http://localhost:8080/app.js:86593:38)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:8080/app.js:15900:15)
    at wrapper [as updateComponent] (http://localhost:8080/app.js:13545:22)
    at ReactCompositeComponentMixin.receiveComponent (http://localhost:8080/app.js:15787:11)
    at Object.ReactReconciler.receiveComponent (http://localhost:8080/app.js:13679:23)
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:8080/app.js:16029:24)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:8080/app.js:16007:11)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:8080/app.js:15923:13)
    at wrapper [as updateComponent] (http://localhost:8080/app.js:13545:22)
```
