### ISSUE TITLE
Cannot launch BitShares client

### ISSUE THREAD

**Issue by mastercyb** [cryptonomex/graphene-ui#782]
I suffer this error from BitShares 2.0 inception and every version I wait that it begin to work, but magic do not happens :-1: 

Client through error during launch

OS X El Capitan:

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at module.exports (/Applications/BitShares2-light.app/Contents/Resources/app.asar/vendor/electron_boilerplate/window_state.js:25:40)
    at /Applications/BitShares2-light.app/Contents/Resources/app.asar/electron.js:15:27
    at Object.<anonymous> (/Applications/BitShares2-light.app/Contents/Resources/app.asar/electron.js:107:3)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/Applications/BitShares2-light.app/Contents/Resources/atom.asar/browser/lib/init.js:108:10)
    at Object.<anonymous> (/Applications/BitShares2-light.app/Contents/Resources/atom.asar/browser/lib/init.js:110:4)
```

**Comment by valzav** [comment]
Looks like the app's state file got corrupted and couldn't be loaded. In the next version I will include exception handler so it will start with an empty state.

**Comment by mastercyb** [comment]
Thanks a lot!
