### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by poqdavid** [cryptonomex/graphene-ui#887]
I been trying to build this project and I am running Window 10 64bit, I changed my python to version 2.7.12 32bit but I still get this errors
http://pastebin.com/raw/xu3PTMu8

here is the npm logs if it helps
[npm-debug.txt](https://github.com/cryptonomex/graphene-ui/files/626362/npm-debug.txt)

**Comment by xeroc** [comment]
It's a dependency that fails to install. I don't think this issue will find alot of eyes looking into it in this repository:
Maybe you can find help in the repo that maintains `node-gyp` (which fails in your case)

```
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  contextify.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifier
s [F:\Projects\graphene-ui\web\node_modules\contextify\build\contextify.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Projects\graphene-ui\web\node_modules\contextify
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Graphene-UI@1.1.0 F:\Projects\graphene-ui\web
`-- babel-loader@5.4.2
  `-- object-assign@3.0.0
```
